Feature/crud patient continuation
gebarros/rails pull request #2
Opened 2018-10-27 16:16 UTC by gebarros

**Descrição:**
Esse PR finaliza a criação do CRUD para a classe pacientes.
Na tela é possível adicionar um novo paciente, editar seus dados, deletar. Além da listagem completa e da opção de visualizar os detalhes.

Os campos ainda não possuem nenhum tipo de validação.

2018-10-27 18:17 UTC, marcosinger requested changes

2018-10-27 18:17 UTC, marcosinger commented on lab/app/views/patients/edit.html.erb
> +<html>
daqui para cima não precisa. Isso já está definido no [template que o Rails usa por padrão](https://github.com/gebarros/rails/blob/master/lab/app/views/layouts/application.html.erb#L1-L2). Vai fica mais claro quando vc começar a ver mais como as views funcionam. Por enquanto, só remover

2018-10-27 18:17 UTC, marcosinger commented on lab/app/views/patients/edit.html.erb
> +            <%= form.label :nome %><br>
nos labels vc sempre usa o mesmo nome do campo, nesse caso `name`. Provavelmente vc fez isso porque quis que aparecesse os nomes em português, certo?

Te mostro como isso funciona quando fizermos o pair. Anota para não esquecer :)

2018-10-27 18:17 UTC, marcosinger commented on lab/app/views/patients/edit.html.erb
> +            <%= form.label :sexo %><br>
aqui é `:gender`. Isso serve para todos os outros abaixo

2018-10-27 18:17 UTC, marcosinger commented on lab/app/views/patients/index.html.erb
> +          <td><%= link_to 'Deletar', patient_path(p), method: :delete, data: { confirm: 'Você tem certeza que quer excluir?' } %>
:star:

2018-10-27 18:17 UTC, marcosinger commented on lab/app/views/patients/new.html.erb
> +<%= form_with scope: :patient, url: patients_path, local: true do |form| %>
:notebook: : me lembra de te ensinar sobre `partials`

2018-10-27 18:17 UTC, marcosinger commented on lab/app/views/patients/show.html.erb
> +<html>
a mesma coisa do outro comentário: pode remover

2018-10-28 01:06 UTC, gebarros commented on lab/app/views/patients/new.html.erb
> +<%= form_with scope: :patient, url: patients_path, local: true do |form| %>
:+1:

2018-10-28 01:06 UTC, gebarros commented on lab/app/views/patients/edit.html.erb
> +            <%= form.label :nome %><br>
:

2018-10-28 01:15 UTC, gebarros commented
Prontinho @marcosinger... alterações realizadas com sucesso!! :-)

2018-10-29 14:45 UTC, marcosinger approved these changes

2018-10-29 14:51 UTC, merged